"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthRoute = void 0;
const express_1 = require("express");
const AuthController_1 = require("../../controllers/AuthController");
const authenticateToken_1 = require("../../middleware/authenticateToken");
const UserController_1 = require("../../controllers/UserController");
const UserService_1 = require("../../services/UserService");
const UserRepo_1 = require("../../repository/UserRepo");
const Users_1 = require("../../models/Users");
exports.AuthRoute = (0, express_1.Router)();
const User_repository = new UserRepo_1.UserRepository(Users_1.UserModel);
const User_Service = new UserService_1.UserService(User_repository);
const User_controller = new UserController_1.UserController(User_Service);
exports.AuthRoute.post("/register", User_controller.Register.bind(User_controller));
exports.AuthRoute.post("/login", User_controller.Login.bind(User_controller));
exports.AuthRoute.post("/confirm-otp", User_controller.verifyOtp.bind(User_controller));
exports.AuthRoute.get("/users", User_controller.show.bind(User_controller));
// AuthRoute.post("/set-username", loginController);
// AuthRoute.post("/profile-pic", loginController);
exports.AuthRoute.get("/refresh-access-token", AuthController_1.refresh_token);
exports.AuthRoute.post("/middleware-testing", authenticateToken_1.authenticateToken, AuthController_1.MiddlewareTesting);
//# sourceMappingURL=authRoute.js.map