name: CI/CD - Build and Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: "npm run build"

      - name: Verify build directory
        run: ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist_old/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist_old/

      - name: Verify artifact content
        run: ls -la ./dist_old/

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          target: /app/
          source: ./dist_old/*
          debug: true # Enable detailed debugging logs
          tar: false

      - name: Restart application on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            mkdir -p /app/  
            cd /app/
            if ! command -v pm2 &> /dev/null; then
            echo "PM2 not found, installing..."
            sudo npm install -g pm2
            fi
            pm2 restart all || pm2 start dist_old/index.js --name "my-app"
