name: build and deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # 'uses' instead of 'use'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Verify build directory
        run: ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: build/
